### ISSUE TITLE
Exception "First modifier for path must be: M or m." incorrectly thrown.

### ISSUE THREAD

**Issue by fietserwin** [nstdio/SVGMagick#3]
See https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands: move to commands are allowed anywhere along a path, the only requirement is that the 1st command on a path is a move to command.

So you can:
- Remove the checkFirstModifier() method (and the call to it) of class \nstdio\svg\shape\Path. (Note that the message was wrong anyway and that by calling moveTo() in the constructor you will always satisfy the SVG specification.
- Always append to property d when moveTo() is called.
- initialize property d to the empty string in the constructor.

Thanks for publicizing this library, it is easy to use.

**Comment by nstdio** [comment]
Hi @fietserwin ,

Thanks for your interest!

Currently I'm unable to reproduce this issue please, could you provide the sample code or test case for it?

**Comment by fietserwin** [comment]
In fact, your test \PathTest::testIdentifiersOrder() reproduces it: this test thinks it is only allowed to use move to commands as the first command on a path, but it isn't.

$path = new Path(..., 0, 0);
$path->lineTo(10, 10)->moveTo(20, 20)->lineTo(30, 30); 

Should be allowed and produce valid svg syntax, try the below svg text on https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_path2:

<!DOCTYPE html>
<html>
<body>

<svg height="400" width="450">
<path id="lineAB" d="M 100 350 l 150 -300 M 375 50 l 150 300" stroke="red" stroke-width="3" fill="none" />
</svg>

</body>
</html>

**Comment by nstdio** [comment]
Yes, you are definitely right.

**Comment by nstdio** [comment]
If you are using `composer` I guess it'll be hard to change code in `vendor` path.
